"""initial schema

Revision ID: 6bb19a751c6c
Revises: 
Create Date: 2026-04-30 19:38:03.896507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_external_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('erp_system', sa.String(length=40), nullable=False),
    sa.Column('erp_model', sa.String(length=80), nullable=True),
    sa.Column('erp_id', sa.String(length=80), nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity', 'local_id', 'erp_system', name='uq_erp_local')
    )
    op.create_table('lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('working_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('garment_type', sa.String(length=80), nullable=True),
    sa.Column('total_sam', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PRODUCTION_MANAGER', 'SUPERVISOR', 'IE', 'OPERATOR', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_code', sa.String(length=60), nullable=False),
    sa.Column('type', sa.Enum('SNLS', 'OL', 'FOA', 'BARTACK', 'BUTTON', 'BUTTONHOLE', 'IRON', 'MANUAL', name='machine_type'), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('WORKING', 'IDLE', 'BREAKDOWN', 'MAINTENANCE', name='machine_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_code')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('op_code', sa.String(length=60), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('sam', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('machine_type', sa.Enum('SNLS', 'OL', 'FOA', 'BARTACK', 'BUTTON', 'BUTTONHOLE', 'IRON', 'MANUAL', name='machine_type'), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'op_code', name='uq_style_opcode')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('base_efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', name='attendance_status'), nullable=False),
    sa.Column('current_line_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_line_id'], ['lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_table('balance_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('target_output_hour', sa.Integer(), nullable=False),
    sa.Column('working_minutes', sa.Integer(), nullable=False),
    sa.Column('available_operators', sa.Integer(), nullable=False),
    sa.Column('takt_time', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('theoretical_ops', sa.Integer(), nullable=True),
    sa.Column('line_efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('balance_loss', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bottleneck_op_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROPOSED', 'APPLIED', 'REJECTED', name='balance_status'), nullable=False),
    sa.Column('solver', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bottleneck_op_id'], ['operations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_telemetry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_precedence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=False),
    sa.Column('successor_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('predecessor_id <> successor_id', name='ck_no_self_precedence'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_precedence_pair')
    )
    op.create_table('operator_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_certified', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'operation_id', name='uq_operator_op')
    )
    op.create_table('time_studies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('captured_by', sa.Uuid(), nullable=True),
    sa.Column('cycle_seconds', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('allowance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('captured_sam', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('cycle_time', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('expected_output', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['balance_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'operation_id', name='uq_run_op')
    )
    op.create_table('hourly_production',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hour_slot', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('actual', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['balance_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rebalance_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('previous_run_id', sa.Integer(), nullable=True),
    sa.Column('new_run_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.Enum('OPERATOR_ABSENT', 'MACHINE_BREAKDOWN', 'TARGET_CHANGE', 'OUTPUT_DEVIATION', 'MANUAL', name='rebalance_trigger'), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('eff_before', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('eff_after', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('output_before', sa.Integer(), nullable=True),
    sa.Column('output_after', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_run_id'], ['balance_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_run_id'], ['balance_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_wip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wip_units', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['balance_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_wip')
    op.drop_table('rebalance_events')
    op.drop_table('hourly_production')
    op.drop_table('balance_assignments')
    op.drop_table('time_studies')
    op.drop_table('operator_skills')
    op.drop_table('operation_precedence')
    op.drop_table('machine_telemetry')
    op.drop_table('balance_runs')
    op.drop_table('operators')
    op.drop_table('operations')
    op.drop_table('machines')
    op.drop_table('users')
    op.drop_table('styles')
    op.drop_table('lines')
    op.drop_table('erp_external_ids')
    # ### end Alembic commands ###
